# Autogenerated wrapper script for atomsk_jll for x86_64-unknown-freebsd
export atomsk

using LAPACK_jll
JLLWrappers.@generate_wrapper_header("atomsk")
JLLWrappers.@declare_executable_product(atomsk)
function __init__()
    JLLWrappers.@generate_init_header(LAPACK_jll)
    JLLWrappers.@init_executable_product(
        atomsk,
        "bin/atomsk",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
